use utoipa::OpenApi;

use crate::application::ai_expense::{
    AiDraftItemData, AiExpenseDraftData, AiExpenseDraftMemberSuggestion, AiMoneyData,
    AiSettingsView, AiSplitParticipantData, AiSplitSuggestionData, AiWarningData,
};

use super::{
    accounting::{
        __path_ledger, __path_recommendations, BalanceData, LedgerData, LedgerEnvelope,
        RecommendationData, RecommendationEnvelope, RecommendationItemData,
        StrategyRecommendationData,
    },
    activity::{
        __path_create, __path_delete as __path_activity_delete, __path_download_cover,
        __path_get as __path_activity_get, __path_list as __path_activity_list,
        __path_list_audit_logs, __path_list_members,
        __path_transfer_ownership as __path_activity_transfer_ownership,
        __path_transition as __path_activity_transition, __path_update as __path_activity_update,
        __path_update_cover_preset, __path_upload_cover, ActivityAuditChangeData,
        ActivityAuditData, ActivityAuditExpenseData, ActivityAuditListEnvelope, ActivityData,
        ActivityEnvelope, ActivityFieldPermissionsData, ActivityLifecycleRequest,
        ActivityListEnvelope, ActivityMemberData, ActivityMemberListEnvelope,
        ActivityUpdateEnvelope, ActivityVersionRequest, CoverBinary, CreateActivityRequest,
        TransferOwnershipRequest, UpdateActivityRequest, UpdateCoverPresetRequest,
        UploadCoverRequest,
    },
    admin::{
        __path_delete_user_account, __path_registration_policy, __path_reset_user_password,
        __path_storage, __path_system_information, __path_update_registration_policy,
        __path_update_role, __path_update_status, __path_users, AdminMutationData,
        AdminMutationEnvelope, AdminPasswordResetRequest, AdminUserData, AdminUserListEnvelope,
        RegistrationPolicyData, RegistrationPolicyEnvelope, RegistrationPolicyRequest, StorageData,
        StorageEnvelope, SystemInformationData, SystemInformationEnvelope, UserRoleRequest,
        UserStatusRequest,
    },
    ai_expense::{
        __path_capabilities as __path_ai_capabilities,
        __path_get_settings as __path_ai_get_settings, __path_image_draft as __path_ai_image_draft,
        __path_text_draft as __path_ai_text_draft,
        __path_update_settings as __path_ai_update_settings, AiCapabilityData,
        AiCapabilityEnvelope, AiExpenseDraftEnvelope, AiImageDraftRequest, AiSettingsEnvelope,
        AiSettingsRequest, AiTextDraftRequest,
    },
    attachment::{
        __path_delete as __path_attachment_delete, __path_download as __path_attachment_download,
        __path_upload as __path_attachment_upload, AttachmentBinary, AttachmentEnvelope,
        UploadAttachmentRequest,
    },
    auth::{
        __path_change_password, __path_csrf, __path_download_avatar_image, __path_login,
        __path_logout, __path_public_registration_policy, __path_register, __path_session,
        __path_update_avatar, __path_update_profile, __path_upload_avatar_image, AvatarBinary,
        AvatarPresetData, AvatarPresetEnvelope, ChangePasswordData, ChangePasswordEnvelope,
        ChangePasswordRequest, CsrfData, CsrfEnvelope, DisplayNameData, DisplayNameEnvelope,
        LoginData, LoginEnvelope, LoginRequest, LogoutData, LogoutEnvelope,
        PublicRegistrationPolicyData, PublicRegistrationPolicyEnvelope, RegisterData,
        RegisterEnvelope, RegisterRequest, SessionData, SessionEnvelope, UpdateAvatarPresetRequest,
        UpdateDisplayNameRequest, UploadAvatarImageRequest,
    },
    collaboration::{
        __path_create_guest, __path_create_guest_binding_invitation, __path_create_invitation,
        __path_decide_join_request, __path_get_invitation_link, __path_get_join_request,
        __path_join_invitation, __path_list_invitations, __path_list_join_requests,
        __path_preview_invitation, __path_remove_guest, __path_revoke_invitation,
        CreateGuestBindingInvitationRequest, CreateGuestRequest, CreateInvitationRequest,
        CreatedInvitationData, CreatedInvitationEnvelope, DecideJoinRequestRequest, GuestData,
        GuestEnvelope, GuestRemovalData, GuestRemovalEnvelope, GuestRemovalResultData,
        InvitationData, InvitationEnvelope, InvitationLinkData, InvitationLinkEnvelope,
        InvitationListEnvelope, InvitationPreviewData, InvitationPreviewEnvelope,
        JoinInvitationData, JoinInvitationEnvelope, JoinRequestData, JoinRequestEnvelope,
        JoinRequestListEnvelope,
    },
    error::{ErrorBody, ErrorEnvelope},
    exchange_rate::{
        __path_suggest as __path_exchange_rate_suggest, ExchangeRateSuggestionData,
        ExchangeRateSuggestionEnvelope,
    },
    expense::{
        __path_create as __path_expense_create, __path_delete as __path_expense_delete,
        __path_get as __path_expense_get, __path_list as __path_expense_list,
        __path_update as __path_expense_update, BillClearingData, CreatedExpenseData,
        CreatedExpenseEnvelope, DeleteExpenseRequest, DeletedExpenseData, DeletedExpenseEnvelope,
        ExpenseAggregateData, ExpenseAttachmentData, ExpenseData, ExpenseDraftRequest,
        ExpenseEnvelope, ExpenseFactData, ExpenseListEnvelope, ExpensePaymentRequest,
        ExpenseSettlementProgressData, ExpenseSplitEntryRequest, ExpenseSplitRequest,
        MemberSettlementProgressData, UpdateExpenseRequest,
    },
    mcp::{
        __path_create_token, __path_list_tokens, __path_revoke_token, CreateMcpTokenRequest,
        CreatedMcpTokenData, CreatedMcpTokenEnvelope, McpTokenData, McpTokenListEnvelope,
    },
    notification::{
        __path_clear as __path_notification_clear, __path_delete as __path_notification_delete,
        __path_list as __path_notification_list,
        __path_mark_all_read as __path_notification_mark_all_read,
        __path_mark_read as __path_notification_mark_read, ClearNotificationsRequest,
        NotificationData, NotificationEnvelope, NotificationFilterData, NotificationListData,
        NotificationListEnvelope,
    },
    push::{
        __path_delete_subscription as __path_push_delete_subscription,
        __path_get_push_settings as __path_push_get_settings,
        __path_register_subscription as __path_push_register_subscription,
        __path_update_push_settings as __path_push_update_settings, PushPreferencesData,
        PushSettingsData, PushSettingsEnvelope, PushSubscriptionData,
        PushSubscriptionDeleteRequest, PushSubscriptionEnvelope, PushSubscriptionKeys,
        PushSubscriptionRequest,
    },
    router::{__path_health, HealthData, HealthEnvelope},
    settlement::{
        __path_create as __path_settlement_create, __path_get as __path_settlement_get,
        __path_list as __path_settlement_list, __path_update as __path_settlement_update,
        __path_void as __path_settlement_void, CreateSettlementRequest, CreatedSettlementData,
        CreatedSettlementEnvelope, SettlementAllocationData, SettlementApplicationData,
        SettlementData, SettlementEnvelope, SettlementEnvelopeData, SettlementListEnvelope,
        UpdateSettlementRequest, VoidSettlementRequest,
    },
    settlement_scope::{
        __path_confirm as __path_confirm_bill_offsets, __path_preview as __path_settlement_preview,
        ConfirmBillOffsetsEnvelope, SettlementPreviewEnvelope,
    },
    sharing::{
        __path_export_csv, __path_summary, ActivitySummaryData, ActivitySummaryEnvelope,
        SummaryBalanceData, SummaryCategoryTotalData, SummaryCurrencyTotalData,
        SummaryRecommendationData,
    },
    snapshot::{
        __path_get as __path_get_activity_snapshot, ActivitySnapshotData, ActivitySnapshotEnvelope,
    },
};

#[derive(OpenApi)]
#[openapi(
    info(title = "HuddleTab API", version = "0.1.0"),
    paths(
        health,
        csrf,
        login,
        register,
        public_registration_policy,
        logout,
        session,
        change_password,
        super::auth::change_username,
        update_avatar,
        upload_avatar_image,
        download_avatar_image,
        update_profile,
        users,
        delete_user_account,
        update_status,
        update_role,
        reset_user_password,
        registration_policy,
        update_registration_policy,
        storage,
        system_information,
        ai_get_settings,
        ai_update_settings,
        ai_capabilities,
        ai_text_draft,
        ai_image_draft,
        create,
        activity_list,
        activity_get,
        list_audit_logs,
        activity_update,
        activity_delete,
        activity_transition,
        activity_transfer_ownership,
        update_cover_preset,
        upload_cover,
        download_cover,
        list_members,
        create_guest,
        remove_guest,
        create_guest_binding_invitation,
        create_invitation,
        list_invitations,
        get_invitation_link,
        revoke_invitation,
        preview_invitation,
        join_invitation,
        list_join_requests,
        get_join_request,
        decide_join_request,
        notification_list,
        notification_mark_read,
        notification_mark_all_read,
        notification_clear,
        notification_delete,
        push_get_settings,
        push_update_settings,
        push_register_subscription,
        push_delete_subscription,
        expense_create,
        expense_list,
        expense_get,
        expense_update,
        expense_delete,
        exchange_rate_suggest,
        attachment_upload,
        attachment_download,
        attachment_delete,
        ledger,
        recommendations,
        get_activity_snapshot,
        summary,
        export_csv,
        settlement_create,
        settlement_preview,
        confirm_bill_offsets,
        settlement_list,
        settlement_get,
        settlement_update,
        settlement_void,
        create_token,
        list_tokens,
        revoke_token
    ),
    components(schemas(
        HealthData,
        HealthEnvelope,
        ErrorBody,
        ErrorEnvelope,
        CsrfData,
        CsrfEnvelope,
        LoginRequest,
        LoginData,
        LoginEnvelope,
        PublicRegistrationPolicyData,
        PublicRegistrationPolicyEnvelope,
        RegisterRequest,
        RegisterData,
        RegisterEnvelope,
        LogoutData,
        LogoutEnvelope,
        SessionData,
        SessionEnvelope,
        super::auth::ChangeUsernameRequest,
        super::auth::ChangeUsernameEnvelope,
        super::auth::ChangeUsernameData,
        ChangePasswordRequest,
        ChangePasswordData,
        ChangePasswordEnvelope,
        UpdateAvatarPresetRequest,
        AvatarBinary,
        UploadAvatarImageRequest,
        AvatarPresetData,
        AvatarPresetEnvelope,
        UpdateDisplayNameRequest,
        DisplayNameData,
        DisplayNameEnvelope,
        AdminUserData,
        AdminUserListEnvelope,
        UserStatusRequest,
        UserRoleRequest,
        AdminPasswordResetRequest,
        AdminMutationData,
        AdminMutationEnvelope,
        RegistrationPolicyData,
        RegistrationPolicyEnvelope,
        RegistrationPolicyRequest,
        StorageData,
        StorageEnvelope,
        SystemInformationData,
        SystemInformationEnvelope,
        AiSettingsView,
        AiSettingsRequest,
        AiSettingsEnvelope,
        AiCapabilityData,
        AiCapabilityEnvelope,
        AiTextDraftRequest,
        AiImageDraftRequest,
        AiExpenseDraftData,
        AiExpenseDraftEnvelope,
        AiMoneyData,
        AiExpenseDraftMemberSuggestion,
        AiSplitParticipantData,
        AiSplitSuggestionData,
        AiDraftItemData,
        AiWarningData,
        CreateActivityRequest,
        CoverBinary,
        UploadCoverRequest,
        UpdateCoverPresetRequest,
        UpdateActivityRequest,
        ActivityLifecycleRequest,
        ActivityVersionRequest,
        TransferOwnershipRequest,
        ActivityData,
        ActivityAuditChangeData,
        ActivityAuditData,
        ActivityAuditExpenseData,
        ActivityAuditListEnvelope,
        ActivityFieldPermissionsData,
        ActivityEnvelope,
        ActivityUpdateEnvelope,
        ActivityListEnvelope,
        ActivityMemberData,
        ActivityMemberListEnvelope,
        CreateGuestRequest,
        GuestData,
        GuestEnvelope,
        GuestRemovalData,
        GuestRemovalEnvelope,
        GuestRemovalResultData,
        CreateGuestBindingInvitationRequest,
        CreateInvitationRequest,
        CreatedInvitationData,
        CreatedInvitationEnvelope,
        InvitationData,
        InvitationEnvelope,
        InvitationLinkData,
        InvitationLinkEnvelope,
        InvitationListEnvelope,
        InvitationPreviewData,
        InvitationPreviewEnvelope,
        JoinInvitationData,
        JoinInvitationEnvelope,
        JoinRequestData,
        JoinRequestEnvelope,
        JoinRequestListEnvelope,
        DecideJoinRequestRequest,
        NotificationData,
        NotificationEnvelope,
        NotificationFilterData,
        ClearNotificationsRequest,
        NotificationListData,
        NotificationListEnvelope,
        PushSettingsData,
        PushSettingsEnvelope,
        PushPreferencesData,
        PushSubscriptionKeys,
        PushSubscriptionRequest,
        PushSubscriptionDeleteRequest,
        PushSubscriptionData,
        PushSubscriptionEnvelope,
        ExpensePaymentRequest,
        ExpenseSplitEntryRequest,
        ExpenseSplitRequest,
        ExpenseDraftRequest,
        UpdateExpenseRequest,
        DeleteExpenseRequest,
        ExpenseData,
        ExpenseFactData,
        ExpenseAggregateData,
        BillClearingData,
        ExpenseSettlementProgressData,
        MemberSettlementProgressData,
        ExpenseAttachmentData,
        UploadAttachmentRequest,
        AttachmentBinary,
        AttachmentEnvelope,
        ExpenseEnvelope,
        CreatedExpenseData,
        CreatedExpenseEnvelope,
        ExpenseListEnvelope,
        DeletedExpenseData,
        DeletedExpenseEnvelope,
        ExchangeRateSuggestionData,
        ExchangeRateSuggestionEnvelope,
        BalanceData,
        LedgerData,
        LedgerEnvelope,
        RecommendationItemData,
        RecommendationData,
        StrategyRecommendationData,
        RecommendationEnvelope,
        ActivitySnapshotData,
        ActivitySnapshotEnvelope,
        ActivitySummaryData,
        ActivitySummaryEnvelope,
        SummaryBalanceData,
        SummaryCurrencyTotalData,
        SummaryCategoryTotalData,
        SummaryRecommendationData,
        CreateSettlementRequest,
        crate::application::settlement::SettlementScope,
        crate::application::settlement_scope::SettlementPreviewRequest,
        crate::application::settlement_scope::SettlementPreview,
        crate::application::settlement_scope::SettlementDateOption,
        crate::application::settlement_scope::ScopeBalance,
        crate::application::settlement_scope::ScopeRecommendation,
        crate::application::settlement_scope::ConfirmBillOffsetsRequest,
        crate::application::settlement_scope::ConfirmBillOffsetsData,
        SettlementPreviewEnvelope,
        ConfirmBillOffsetsEnvelope,
        UpdateSettlementRequest,
        VoidSettlementRequest,
        SettlementData,
        SettlementAllocationData,
        SettlementApplicationData,
        SettlementEnvelopeData,
        SettlementEnvelope,
        CreatedSettlementData,
        CreatedSettlementEnvelope,
        SettlementListEnvelope,
        CreateMcpTokenRequest,
        McpTokenData,
        CreatedMcpTokenData,
        CreatedMcpTokenEnvelope,
        McpTokenListEnvelope
    ))
)]
struct ApiDoc;

#[must_use]
pub fn document() -> utoipa::openapi::OpenApi {
    ApiDoc::openapi()
}
