use utoipa::OpenApi;

use super::{
    accounting::{
        __path_ledger, __path_recommendations, BalanceData, LedgerData, LedgerEnvelope,
        RecommendationData, RecommendationEnvelope, RecommendationItemData,
    },
    activity::{
        __path_create, __path_delete as __path_activity_delete, __path_get as __path_activity_get,
        __path_list as __path_activity_list, __path_list_members,
        __path_restore as __path_activity_restore, __path_transition as __path_activity_transition,
        __path_update as __path_activity_update, ActivityData, ActivityEnvelope,
        ActivityFieldPermissionsData, ActivityLifecycleRequest, ActivityListEnvelope,
        ActivityMemberData, ActivityMemberListEnvelope, ActivityUpdateEnvelope,
        ActivityVersionRequest, CreateActivityRequest, UpdateActivityRequest,
    },
    auth::{
        __path_change_password, __path_csrf, __path_login, __path_logout, __path_register,
        __path_session, ChangePasswordData, ChangePasswordEnvelope, ChangePasswordRequest,
        CsrfData, CsrfEnvelope, LoginData, LoginEnvelope, LoginRequest, LogoutData, LogoutEnvelope,
        RegisterData, RegisterEnvelope, RegisterRequest, SessionData, SessionEnvelope,
    },
    collaboration::{
        __path_create_guest, __path_create_guest_binding_invitation, __path_create_invitation,
        __path_decide_join_request, __path_get_join_request, __path_join_invitation,
        __path_list_invitations, __path_list_join_requests, __path_preview_invitation,
        __path_revoke_invitation, CreateGuestBindingInvitationRequest, CreateGuestRequest,
        CreateInvitationRequest, CreatedInvitationData, CreatedInvitationEnvelope,
        DecideJoinRequestRequest, GuestData, GuestEnvelope, InvitationData, InvitationEnvelope,
        InvitationListEnvelope, InvitationPreviewData, InvitationPreviewEnvelope,
        JoinInvitationData, JoinInvitationEnvelope, JoinRequestData, JoinRequestEnvelope,
        JoinRequestListEnvelope,
    },
    error::{ErrorBody, ErrorEnvelope},
    expense::{
        __path_create as __path_expense_create, __path_delete as __path_expense_delete,
        __path_get as __path_expense_get, __path_list as __path_expense_list,
        __path_update as __path_expense_update, CreatedExpenseData, CreatedExpenseEnvelope,
        DeleteExpenseRequest, DeletedExpenseData, DeletedExpenseEnvelope, ExpenseAggregateData,
        ExpenseData, ExpenseDraftRequest, ExpenseEnvelope, ExpenseFactData, ExpenseListEnvelope,
        ExpensePaymentRequest, ExpenseSplitEntryRequest, ExpenseSplitRequest, UpdateExpenseRequest,
    },
    notification::{
        __path_list as __path_notification_list, __path_mark_read as __path_notification_mark_read,
        NotificationData, NotificationEnvelope, NotificationListData, NotificationListEnvelope,
    },
    router::{__path_health, HealthData, HealthEnvelope},
    settlement::{
        __path_create as __path_settlement_create, __path_get as __path_settlement_get,
        __path_list as __path_settlement_list, __path_update as __path_settlement_update,
        __path_void as __path_settlement_void, CreateSettlementRequest, CreatedSettlementData,
        CreatedSettlementEnvelope, SettlementData, SettlementEnvelope, SettlementEnvelopeData,
        SettlementListEnvelope, UpdateSettlementRequest, VoidSettlementRequest,
    },
    sharing::{
        __path_export_csv, __path_summary, ActivitySummaryData, ActivitySummaryEnvelope,
        SummaryBalanceData, SummaryRecommendationData,
    },
    snapshot::{
        __path_get as __path_get_activity_snapshot, ActivitySnapshotData, ActivitySnapshotEnvelope,
    },
};

#[derive(OpenApi)]
#[openapi(
    info(title = "HuddleTab API", version = "0.1.0"),
    paths(
        health,
        csrf,
        login,
        register,
        logout,
        session,
        change_password,
        create,
        activity_list,
        activity_get,
        activity_update,
        activity_delete,
        activity_transition,
        activity_restore,
        list_members,
        create_guest,
        create_guest_binding_invitation,
        create_invitation,
        list_invitations,
        revoke_invitation,
        preview_invitation,
        join_invitation,
        list_join_requests,
        get_join_request,
        decide_join_request,
        notification_list,
        notification_mark_read,
        expense_create,
        expense_list,
        expense_get,
        expense_update,
        expense_delete,
        ledger,
        recommendations,
        get_activity_snapshot,
        summary,
        export_csv,
        settlement_create,
        settlement_list,
        settlement_get,
        settlement_update,
        settlement_void
    ),
    components(schemas(
        HealthData,
        HealthEnvelope,
        ErrorBody,
        ErrorEnvelope,
        CsrfData,
        CsrfEnvelope,
        LoginRequest,
        LoginData,
        LoginEnvelope,
        RegisterRequest,
        RegisterData,
        RegisterEnvelope,
        LogoutData,
        LogoutEnvelope,
        SessionData,
        SessionEnvelope,
        ChangePasswordRequest,
        ChangePasswordData,
        ChangePasswordEnvelope,
        CreateActivityRequest,
        UpdateActivityRequest,
        ActivityLifecycleRequest,
        ActivityVersionRequest,
        ActivityData,
        ActivityFieldPermissionsData,
        ActivityEnvelope,
        ActivityUpdateEnvelope,
        ActivityListEnvelope,
        ActivityMemberData,
        ActivityMemberListEnvelope,
        CreateGuestRequest,
        GuestData,
        GuestEnvelope,
        CreateGuestBindingInvitationRequest,
        CreateInvitationRequest,
        CreatedInvitationData,
        CreatedInvitationEnvelope,
        InvitationData,
        InvitationEnvelope,
        InvitationListEnvelope,
        InvitationPreviewData,
        InvitationPreviewEnvelope,
        JoinInvitationData,
        JoinInvitationEnvelope,
        JoinRequestData,
        JoinRequestEnvelope,
        JoinRequestListEnvelope,
        DecideJoinRequestRequest,
        NotificationData,
        NotificationEnvelope,
        NotificationListData,
        NotificationListEnvelope,
        ExpensePaymentRequest,
        ExpenseSplitEntryRequest,
        ExpenseSplitRequest,
        ExpenseDraftRequest,
        UpdateExpenseRequest,
        DeleteExpenseRequest,
        ExpenseData,
        ExpenseFactData,
        ExpenseAggregateData,
        ExpenseEnvelope,
        CreatedExpenseData,
        CreatedExpenseEnvelope,
        ExpenseListEnvelope,
        DeletedExpenseData,
        DeletedExpenseEnvelope,
        BalanceData,
        LedgerData,
        LedgerEnvelope,
        RecommendationItemData,
        RecommendationData,
        RecommendationEnvelope,
        ActivitySnapshotData,
        ActivitySnapshotEnvelope,
        ActivitySummaryData,
        ActivitySummaryEnvelope,
        SummaryBalanceData,
        SummaryRecommendationData,
        CreateSettlementRequest,
        UpdateSettlementRequest,
        VoidSettlementRequest,
        SettlementData,
        SettlementEnvelopeData,
        SettlementEnvelope,
        CreatedSettlementData,
        CreatedSettlementEnvelope,
        SettlementListEnvelope
    ))
)]
struct ApiDoc;

#[must_use]
pub fn document() -> utoipa::openapi::OpenApi {
    ApiDoc::openapi()
}
